### ISSUE TITLE
Refactoring names of public attributes breaks/does not update the serialised data inside the unity project

### ISSUE THREAD

**Issue by sfjohansson** [consulo/consulo-unity3d#114]
Refactoring the name of a public attribute will break the serialised data inside the unity project( i.e. it will be lost). I tried this on unity 2017 and I believe it also applied to 5.6.

**Comment by VISTALL** [comment]
Hi. I'm not undestand correctly, **serialised data inside the unity project** you talking about ***.unity** files?

Thanks.

**Comment by sfjohansson** [comment]
If you have script with a public field...and rename the public field inside consulo...then when you go back to unity..the field would have lost it's value.

**Comment by sfjohansson** [comment]
It works fine to rename the whole class...

**Comment by VISTALL** [comment]
> .the field would have lost it's value.

Inside unity scene? 

I think yes. It's a problem.

Unity scene files can be in two formats:
* Binary format is proprietary (and can't be changed)
* Text format - it's YML format. Then you set value to field, they add `some line` to YML file. But - there no logic for correct searching ClassName+FieldName inside this YML file.
Class renaming works due Unity bind to ***.cs file** (via guid from meta)

Thanks

**Comment by sfjohansson** [comment]
Hmm...Feels like it should work if it is set to force text
Inside prefabs...they are serialised something like this...

--- !u!1 &145968
GameObject:
  m_ObjectHideFlags: 1
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 100100000}
  serializedVersion: 4
  m_Component:
  - 4: {fileID: 420646}
  - 114: {fileID: 11422676}
  m_Layer: 8
  m_Name: Sprite
  m_TagString: Untagged
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1

**Comment by VISTALL** [comment]
Yeah. For correct rename need fully understand file (there no documentation for it).

For example - if in prefab(unity) files we attach two classes (and they contains fields with same names) - and field rename will change **all** lines (for all classes not only our field owner)

Thanks

**Comment by sfjohansson** [comment]
hmm... you also get the GUID of the script  m_Script: {fileID: 11500000, guid: d6182078c651647c9a34e8a33045ac0d, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  thisIsPublicStringDog: Dog

So if the refactoring is done by looking up at the references to the script and then renaming only within that scope

**Comment by sfjohansson** [comment]
With that you could also get a function that look up all the assigned values of a field inside the unity project

**Comment by VISTALL** [comment]
>> With that you could also get a function that look up all the assigned values of a field inside the unity project

yeah already thought about that (year ago). But i couldn't fully understand YML file :(

**Comment by sfjohansson** [comment]
inside the unity scene files it looks like this.. (at least today..maybe it was different before)

--- !u!114 &1145596112
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1145596111}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: d6182078c651647c9a34e8a33045ac0d, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  thisIsPublicStringPigeon: Mouse
  thisIsPublicInt: 23
  nestedClass:
    mandatory: 1
    countable: 0
    isMissionCritical: 1
    startPriority: 0
    cargoShipObjective: 0
    objectiveTargetIsOnCargoShip: 0
    cargoShipNumber: 0
    objectiveTargetNameOnShip: cool objective name
    objectiveTargetIsOnPlayerVehicle: 0
    displayName:
      refnr: 0
      fieldid: 
      category: 
      place: 
      english: []
      voiceenglish: []
      chinesetraditional: []
      voicechinesetraditional: []
      chinesesimplified: []
      voicechinesesimplified: []
      french: []
      frenchvoice: []
      german: []
      germanvoice: []
      japanese: []
      voicejapanese: []
      portuguese: []
      voiceportuguese: []
      russian: []
      voicerussian: []
      spanish: []
      voicespanish: []
      swedish: []
      voiceswedish: []
    displayFailText:
      refnr: 0
      fieldid: 
      category: 
      place: 
      english: []
      voiceenglish: []
      chinesetraditional: []
      voicechinesetraditional: []
      chinesesimplified: []
      voicechinesesimplified: []
      french: []
      frenchvoice: []
      german: []
      germanvoice: []
      japanese: []
      voicejapanese: []
      portuguese: []
      voiceportuguese: []
      russian: []
      voicerussian: []
      spanish: []
      voicespanish: []
      swedish: []
      voiceswedish: []
    name: 
    failText: 
    displaySetting: 0
    displayFormat: 0
    startTrigger: 0
    targetRelationship: 0
    delayBetweenTargetSwitching: 0
    controlRelationship: 0
    noObjectiveTargetsEqualsFail: 0
    completionBehaviour: 0
    allowMultipleAttempts: 0
    abortResets: 0
    successCriteria: 0
    successThreshold: 1
    category: 0
    scoreContributionWeight: 1
    scoreRatingCalculation: 0
    progressCalculation: 0

**Comment by sfjohansson** [comment]
the [System.Serializable] nestedClass" don't have a guid assigned which could be a problem...but finding all declarations and then processing the corresponding textfields  by name could work

**Comment by sfjohansson** [comment]
I might of course be completely crazy...and there will be problems =O

**Comment by VISTALL** [comment]
> ...and there will be problems =O

Yeah, i will try to understand format(and play with implementation) at weekends. 

Thanks

**Comment by sfjohansson** [comment]
It certainly would be a great feature to be able refactoring all naming freely... :)

**Comment by VISTALL** [comment]
Checked.

For my first look - format simple.
Need all keys for future analyze, it's:

* MonoBehaviour (in unity scene)
```yml
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_GameObject: {fileID: 1085037891}
  m_Enabled: 1
  m_EditorHideFlags: 0
  m_Script: {fileID: 11500000, guid: 38b5c2f743cd8034a8beeebf277c92c1, type: 3}
  m_Name: 
  m_EditorClassIdentifier: 
  speed: 30
```
others ?

**Comment by VISTALL** [comment]
plus
* Prefab
* Transform
* GameObject
* TrailRenderer

for prefabs

**Comment by VISTALL** [comment]
Some feature from scene indexing

![](http://klikr.org/1c42d2460f2ddbc12012475b968e.gif)

**Comment by sfjohansson** [comment]
Cool...just like that..looks pretty awesome! :) 

Just seeing what values have been assigned without having to go into unity and dig around is super useful already.

How does it feel when you poked around...do you think it would be also "safe" to support refactoring of names?

**Comment by sfjohansson** [comment]
Let me know if you want me to check or try something here :)

**Comment by VISTALL** [comment]
> How does it feel when you poked around...do you think it would be also "safe" to support refactoring of names?

I tired. Field refactoring is more harder task - think on weekends.

I pushed this changes to upstream - just wait for channel update.

**Comment by sfjohansson** [comment]
I can imagine...pretty awesome though that you managed to get the inspection in...I look forward to take them for a test drive  it when the updates comes through..let you know how it goes! 🥇

**Comment by VISTALL** [comment]
Hello!

I'm implemented this feature. For me all works (tested with 100+ unity scene files)

Now field searching - search inside Unity files too.

![](http://klikr.org/bd32c2dc2bebb4a619fe4169e056.png)

And renaming works too.

If you found bugs - report it.

You can try it - switch to nightly channel or wait iteration (https://github.com/consulo/consulo/wiki/Update-channels).

Thanks.

**Comment by VISTALL** [comment]
Gif

![](http://klikr.org/0b2b0bb05403ea055f64a1ebf42a.gif)

**Comment by sfjohansson** [comment]
This is very cool :) been testing it during he day...one thing so far... it would be useful to also see the name of the Game Object that the script is on in addition to the scene.

I still have the old "bug" were it seems that Consulo in fails to index all occurrences of script inside the unity project, I'll take the opportunity to try to look at that while I'm testing this

Awesome work!

**Comment by VISTALL** [comment]
> it would be useful to also see the name of the Game Object that the script is on in addition to the scene.

Not understand about that

Thanks

**Comment by sfjohansson** [comment]
The monobehaviour is attached to a GameObject inside the scene...so in the "Find Usages" could also give you the name of that GameObject, here it is inside the scene file:

--- !u!1 &981505616
GameObject:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  serializedVersion: 5
  m_Component:
  - component: {fileID: 981505617}
  - component: {fileID: 981505619}
  - component: {fileID: 981505618}
  - component: {fileID: 981505620}
  - component: {fileID: 981505621}
  m_Layer: 8
  m_Name: MapIcon + 1
  m_TagString: Untagged
  m_Icon: {fileID: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 0
--- !u!4 &981505617

**Comment by VISTALL** [comment]
You talking about **m_Name**. But i can't understand show link it to field in class (not see guid key)

Can you use https://help.github.com/articles/creating-and-highlighting-code-blocks/ for code, due for default - github is broking indent (but for yaml it's important)

> I still have the old "bug" were it seems that Consulo in fails to index all occurrences of script inside the unity project, I'll take the opportunity to try to look at that while I'm testing this

Outside **Assets** directory ? or wat?

Thanks

**Comment by sfjohansson** [comment]
Looking inside the yaml file... each GameObect inside the scene is listed followed by the mono behaviours attached to it. So you only have to find the first game object declared above a field...or at least I think so =O

GameObject:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 100002, guid: 0019e8e680f2444c4bab1d54c757df74, type: 2}
  m_PrefabInternal: {fileID: 795391858}
  serializedVersion: 4
  m_Component:
  - 4: {fileID: 236570102} **These are the components**
  - 114: {fileID: 236570103}
  m_Layer: 0
  m_Name: PickupSlot **This is the name**
  m_TagString: Untagged
  m_Icon: {fileID: -196007500, guid: 0000000000000000d000000000000000, type: 0}
  m_NavMeshLayer: 0
  m_StaticEditorFlags: 0
  m_IsActive: 1

**Comment by sfjohansson** [comment]
> Outside Assets directory ? or wat?

No they are inside the project...as everything else... =(

**Comment by VISTALL** [comment]
> 4: {fileID: 236570102} **These are the components**

and where i can find this ID ? **236570102** i have no idea

**Comment by sfjohansson** [comment]
Let me dig through unity the files properly..and see what I can find out :)

**Comment by VISTALL** [comment]
It's YAML document id. 

```yaml
--- !u!4 &1757122065
Transform:
```

down

```yaml
GameObject:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 100000, guid: c2a9f8d982bd6f2409a339e9d6a842a6, type: 2}
  m_PrefabInternal: {fileID: 515477041}
  serializedVersion: 5
  m_Component:
  - component: {fileID: 1757122065}
  - component: {fileID: 1777777305}
```

**Comment by VISTALL** [comment]
GameObject name in tooltips, testing
![](http://klikr.org/7396c1e83cb1aff18ef5f7917ff4.png)

**Comment by VISTALL** [comment]
pushed to upstream

**Comment by sfjohansson** [comment]
I've tried grabbing from the alpha channel and I'm getting "Plugin Manager: Following plugins are incompatible with current IDE build: .... " I got build : #1827

**Comment by VISTALL** [comment]
Please delete* this build (1827) from platform directory (https://github.com/consulo/consulo/wiki/Paths-to-system-directories)

I am testing some platform changes, and had broked my Jenkins :( working on fixing . (1827 build deleted)

If need - download 1824 build https://hub.consulo.io/#!repo/alpha/consulo-mac-no-jre

Sorry

**Comment by sfjohansson** [comment]
Deleted and downloaded build 1824. not getting the errors but the unity plugin seems broken in the sense that I don't see the icon next to classes... it is loaded active... I can do the "re-import project".

**Comment by VISTALL** [comment]
Check plugin list - maybe they disabled. (again sorry)

**Comment by sfjohansson** [comment]
No worries... :) They look enabled... =O

**Comment by VISTALL** [comment]
Fixed?

**Comment by sfjohansson** [comment]
Just fetched the latest build... 1832 and now the unity plugin loads. :)

I can see the names of the game object in the tooltip..great stuff! It would be very nice if it would also be listed down in the "find usages" section below for consistency.

<img width="674" alt="screen shot 2017-09-03 at 10 39 59" src="https://user-images.githubusercontent.com/912814/30001966-04f46244-9096-11e7-8bd6-ce45af0679c9.png">

Also I think it would be a lost opportunity not listing the name of the prefab/other game object/file  when the field refers to one.

<img width="976" alt="screen shot 2017-09-03 at 10 40 31" src="https://user-images.githubusercontent.com/912814/30001949-40049d3c-9095-11e7-87cc-4cd318691021.png">

**Comment by sfjohansson** [comment]
The function of opening up the asset in unity is actually dangerous. Because it ditches the current scene in unity, which might have unsaved changes.

Having a warning popup if that is the case would be preferred...or just a "are you sure" dialog.  

The plugin could probably send a message to unity to save current changes...if the user chooses to.

**Comment by sfjohansson** [comment]
Also it would be great if the "Find Usages" on the class itself would also list scenes or prefabs it is sued in.

**Comment by VISTALL** [comment]
Hi. So ugly. I'm thinking about UI for classes & scenes, we can't show all info in tooltip.

> The function of opening up the asset in unity is actually dangerous. Because it ditches the current scene in unity, which might have unsaved changes.

As i remember - unity ask about unsaved changes. If not - yeah it's a problem

**Comment by sfjohansson** [comment]
hehe yeah it can get a little busy there... =O 

don't know if it is possible to add a unity icon to the filter in find usages, but using that UI feels like the natural place to put it.

<img width="599" alt="screen shot 2017-09-03 at 21 29 43" src="https://user-images.githubusercontent.com/912814/30006393-657a1394-90ef-11e7-9f24-d809b9e02d12.png">

**Comment by VISTALL** [comment]
Replaced option in prefab. Now you can call Find usages

![](http://klikr.org/888b7cf407a42d9bfebd93224b4a.png)

**Comment by VISTALL** [comment]
And reworked value view.

![](http://klikr.org/d34edbbdcea6d1be589d6d2552ca.png)

**Comment by VISTALL** [comment]
pushed to upstream. Please test it, and say me your impressions

Thanks

**Comment by sfjohansson** [comment]
Here we go... it's much more navigable but the plain formatting makes it difficult to read:

<img width="800" alt="screen shot 2017-09-03 at 23 11 05" src="https://user-images.githubusercontent.com/912814/30007049-b63f5bf0-90fd-11e7-8362-ff95b03052f2.png">

**Comment by VISTALL** [comment]
Maybe value sorting? And I will thinking about improve presentation

**Comment by sfjohansson** [comment]
Hmm think some kind of column thing...thats why I though the "find usages" if customisable as it already have some filtering options could do well.

Most simple clean up would be to simplify path...  So you probably just want Value+Main File + GameObject that the script is attached to

**Comment by sfjohansson** [comment]
In this case by random I had number...but sorting that would not really make a difference but in some cases i guess it would

**Comment by VISTALL** [comment]
Some new variant of presentation

![](http://klikr.org/b3da0688258297fc6cdbdff2b9be.png)

**Comment by sfjohansson** [comment]
that looks much better already

**Comment by sfjohansson** [comment]
Is it possible to add functionality to the find usages field at the bottom?

**Comment by VISTALL** [comment]
Nope:( Need call find usage manually. I think i will push this change - due it more readable

**Comment by sfjohansson** [comment]
Cool...I'll look forward take it out for a spin tomorrow ..time to go to bed for today! =O

**Comment by VISTALL** [comment]
2:15 am. Oh. 

Finished. Good night

Thanks

**Comment by VISTALL** [comment]
update field value presentation

![](http://klikr.org/838fa3f0e8e490f3a15ca316264f.png)

![](http://klikr.org/0a766b04eddd68d4f5d8ed780d00.png)

![](http://klikr.org/436d06b63db8a945875a133375bb.png)

**Comment by sfjohansson** [comment]
Good morning, cool I'll give it a test drive! :)

**Comment by sfjohansson** [comment]
I think it feels noisy.... what is most of interest is what value is assigned and were. So you want those things to pop out.

So this is what I'm getting when looking at float field:

<img width="930" alt="screen shot 2017-09-04 at 09 36 51" src="https://user-images.githubusercontent.com/912814/30018463-d66cd234-9154-11e7-95bd-37d2f9206845.png">

so more like this
(float) 400 my_prefab.prefab <-AttachedGameObjectName
(float) 400 my_scene.scene <-AttachedGameObjectName

Alt maybe have it by section:

my_scene.scene
(float) 400  -> AttachedGameObjectName_1
(float) 400  -> AttachedGameObjectName_Another_Obj

my_prefab.prefab 
(float) 400  -> AttachedGameObjectName_1
(float) 400  -> AttachedGameObjectName_Another_Obj

**Comment by VISTALL** [comment]
oh. I forgot - primitives structs too :D

**Comment by VISTALL** [comment]
fixed this bug(i added struct view - and it override primitive view)
