### ISSUE TITLE
Can't verify if Consulo UPM packages are working

### ISSUE THREAD

**Issue by TCROC** [consulo/consulo-unity3d#184]
I tried to verify if Consulo can load UPM packages, but the nightly build of the Unity Plugin isn't currently working.  This is in relation to the comment on the issue here: https://github.com/consulo/consulo-unity3d/issues/182#issuecomment-736011327

**Comment by TCROC** [comment]
![image](https://user-images.githubusercontent.com/24307049/100658728-8a29de80-331d-11eb-8698-15999494c597.png)

Here is a snip of the error.

OS: Ubuntu 18.04

**Comment by VISTALL** [comment]
Hello. Ignored message about plugins error update. Must be fixed now

**Comment by TCROC** [comment]
I will test it out.  Should I be using nightly?

**Comment by VISTALL** [comment]
Yeah, but not ignore update plugins error (update only if all plugins available)

**Comment by TCROC** [comment]
@VISTALL Thanks for the quick reply and fix!  So I finally got around to testing out the bug.  Embedded libraries seem to be working.  Git upm is still broken though.  This can be seen with this repo here: https://github.com/TCROC/ConsuloBug.

This issue can be closed, but the issue here: https://github.com/consulo/consulo-unity3d/issues/182 should be reopened.

**Comment by TCROC** [comment]
Just checking in to see what the status of this issue is

**Comment by VISTALL** [comment]
Hello. You used Reimport Unity Project after update?

**Comment by TCROC** [comment]
I did not do a reimport.  I will give that a try and see what happens

**Comment by TCROC** [comment]
I tried the reimport and keep getting this error:

![image](https://user-images.githubusercontent.com/24307049/100905016-99cc3300-3495-11eb-84fc-902e27365a5a.png)

OS: Ubuntu 18.04
Unity Version: ~~2019.4.14f1~~ 2019.4.13f1

**Comment by VISTALL** [comment]
It's warning. Consulo can't calculate ALL defines, and it try fetch from UnityEditor(plugin required).

You can ignore it

**Comment by TCROC** [comment]
Ok even when I ignore that issue, the git upm packages still aren't loading. Do I by any chance need to delete the .consulo folder so it does a completely fresh reimport?

**Comment by VISTALL** [comment]
It will not help. Strange now i can't open project

![image](https://user-images.githubusercontent.com/542934/100906328-1f71d200-34da-11eb-8188-4e34d62c8d03.png)

This project you opened it before in Unity? Unity will resolve Git repo

**Comment by TCROC** [comment]
Ah I know why that error is occurring. It is working on my machine because
then UPM package is cached. That link is currently broken. I’ll push up a
fix with a working link

**Comment by TCROC** [comment]
I fixed the project.  You should be able to pull down the changes and test it out now.  I double checked with this project and the git upm package still isn't loading with this project, even with the fixed link.

**Comment by VISTALL** [comment]
Looks like i removed some code while tests. Pushed fix

Check for Updates
Restart
Reimport Unity Project

**Comment by TCROC** [comment]
I tested it in that project and it appears to work!  :)  I'm going to test it in our main project quick and see how that goes :)

**Comment by TCROC** [comment]
Yay!  Its's working now! :)  When will this be pushed to the release channel?

**Comment by VISTALL** [comment]
> Yay! Its's working now! :) When will this be pushed to the release channel?

Maybe after two weeks.
